# Generated by Django 6.0.1 on 2026-02-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('posts', '0002_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('post', 'author')},
        ),
    ]
