# Generated by Django 6.0.1 on 2026-02-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('posts', '0003_rename_user_bookmark_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('post', 'user')},
        ),
    ]
